version: "3.8"

services:
  mysql-db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"

  # backend:
  #   build:
  #     context: .
  #     dockerfile: docker/django/Dockerfile
  #   env_file: .env
  #   restart: always
  #   volumes:
  #     - .:/app/
  #   depends_on:
  #     - mysql-db
  #   working_dir: "/app/mysql_example"
  #   expose:
  #     - 8000
  #   ports:
  #     - "8000:8000"
  #   command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  mysql_data:
